language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh && bash -ex .travis-ocaml.sh
  - D=$(pwd) && cd /tmp && sudo apt-get install wget && wget "http://yices.csl.sri.com/cgi-bin/yices2-newnewdownload.cgi?file=yices-2.4.2-x86_64-unknown-linux-gnu-static-gmp.tar.gz&accept=I+Agree" && tar -xzf "yices2-newnewdownload.cgi?file=yices-2.4.2-x86_64-unknown-linux-gnu-static-gmp.tar.gz&accept=I+Agree" && cd yices-2.4.2/ && ./install-yices here && cd $D
before_script:
  - opam install -y ocamlbuild ounit menhir ocamlfind
env:
  - OCAML_VERSION=4.01
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
os:
  - linux
script:
  - eval $(opam config env) && YICESDIR=/tmp/yices-2.4.2/bin/ make all && YICESDIR=/tmp/yices-2.4.2/bin/ make check
