language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh && bash -ex .travis-ocaml.sh
  - sudo apt-get install wget &&  cd /tmp && wget "http://yices.csl.sri.com/cgi-bin/yices2-newnewdownload.cgi?file=yices-2.4.2-x86_64-unknown-linux-gnu-static-gmp.tar.gz&accept=I+Agree" && tar -xzf "yices-2.4.2-x86_64-unknown-linux-gnu-static-gmp.tar.gz&accept=I+Agree" && cd yices-2.4.2/ && ./install-yices here
before_script:
  - opam install -y ocamlbuild ounit menhir ocamlfind
env:
  - OCAML_VERSION=4.01
  - OCAML_VERSION=4.02
os:
  - linux
script:
  - YICESDIR=/tmp/yices-2.4.2/bin/ eval $(opam config env) && make all && make check
