(set-logic QF_LIA)
(declare-fun N () Int)
(declare-range A (0 N))
(declare-fun a () (Array A Bool)) 
(assert (>= N 1))
(assert (= (# w A (and (select a w) (= w 0))) 1))
(check-sat)
(assert (= (# w A (not (select a w))) N))
(check-sat)
(get-model)
