(set-logic QF_LIA)
(declare-fun N () Int)
(assert (>= N 1))
(declare-range A (1 N))
(declare-fun a () (Array A Bool)) 
(declare-fun b () (Array A Bool)) 
(declare-fun c () (Array A Bool)) 
(declare-fun half () Int)
(assert (= (# ind A (=
	(select a ind)
	(select b ind)
	)) half))
(assert (= (# ind A (=
	(select a ind)
	(select c ind)
	)) half))
(assert (= (# ind A (=
	(select b ind)
	(not (select c ind))
	)) half))
(check-sat)
(push 1)
(assert (= (* 3 half) (* 2 N)))
(check-sat)
(pop 1)
(push 1)
(assert (= (* 2 half) N))
(check-sat)
(pop 1)
